export const olympics = [
    {
      "ID": 6934,
      "Name": "Angie Lee Bainbridge",
      "Sex": "F",
      "Team": "Australia",
      "Year": 2008,
      "City": "Beijing",
      "Sport": "Swimming",
      "Event": "Swimming Women's 4 x 200 metres Freestyle Relay",
      "Medal": "Gold"
    },
    {
      "ID": 8051,
      "Name": "Bronte Amelia Arnold Barratt",
      "Sex": "F",
      "Team": "Australia",
      "Year": 2008,
      "City": "Beijing",
      "Sport": "Swimming",
      "Event": "Swimming Women's 4 x 200 metres Freestyle Relay",
      "Medal": "Gold"
    },
    {
      "ID": 17684,
      "Name": "Bronte Campbell",
      "Sex": "F",
      "Team": "Australia",
      "Year": 2016,
      "City": "Rio de Janeiro",
      "Sport": "Swimming",
      "Event": "Swimming Women's 4 x 100 metres Freestyle Relay",
      "Medal": "Gold"
    },
    {
      "ID": 17687,
      "Name": "Cate Natalie Campbell",
      "Sex": "F",
      "Team": "Australia",
      "Year": 2016,
      "City": "Rio de Janeiro",
      "Sport": "Swimming",
      "Event": "Swimming Women's 4 x 100 metres Freestyle Relay",
      "Medal": "Gold"
    },
    {
      "ID": 44745,
      "Name": "Kosuke Hagino",
      "Sex": "M",
      "Team": "Japan",
      "Year": 2016,
      "City": "Rio de Janeiro",
      "Sport": "Swimming",
      "Event": "Swimming Men's 400 metres Individual Medley",
      "Medal": "Gold"
    },
    {
      "ID": 57212,
      "Name": "Rie Kaneto",
      "Sex": "F",
      "Team": "Japan",
      "Year": 2016,
      "City": "Rio de Janeiro",
      "Sport": "Swimming",
      "Event": "Swimming Women's 200 metres Breaststroke",
      "Medal": "Gold"
    },
    {
      "ID": 10257,
      "Name": "Joseph Gunnar Bentz",
      "Sex": "M",
      "Team": "United States",
      "Year": 2016,
      "City": "Rio de Janeiro",
      "Sport": "Swimming",
      "Event": "Swimming Men's 4 x 200 metres Freestyle Relay",
      "Medal": "Gold"
    },
    {
      "ID": 10337,
      "Name": "Richard Ricky Berens",
      "Sex": "M",
      "Team": "United States",
      "Year": 2008,
      "City": "Beijing",
      "Sport": "Swimming",
      "Event": "Swimming Men's 4 x 200 metres Freestyle Relay",
      "Medal": "Gold"
    },
    {
      "ID": 45525,
      "Name": "Vincent Hancock",
      "Sex": "M",
      "Team": "United States",
      "Year": 2008,
      "City": "Beijing",
      "Sport": "Shooting",
      "Event": "Shooting Men's Skeet",
      "Medal": "Gold"
    },
    {
      "ID": 120121,
      "Name": "Virginia Ginny Thrasher",
      "Sex": "F",
      "Team": "United States",
      "Year": 2016,
      "City": "Rio de Janeiro",
      "Sport": "Shooting",
      "Event": "Shooting Women's Air Rifle, 10 metres",
      "Medal": "Gold"
    },
    {
      "ID": 111661,
      "Name": "Catherine Skinner",
      "Sex": "F",
      "Team": "Australia",
      "Year": 2016,
      "City": "Rio de Janeiro",
      "Sport": "Shooting",
      "Event": "Shooting Women's Trap",
      "Medal": "Gold"
    },
    {
      "ID": 11146,
      "Name": "Jamie Lynn Beyerle",
      "Sex": "F",
      "Team": "United States",
      "Year": 2012,
      "City": "London",
      "Sport": "Shooting",
      "Event": "Shooting Women's Small-Bore Rifle, Three Positions, 50 metres",
      "Medal": "Gold"
    },
    {
      "ID": 90856,
      "Name": "Kylie Jayne Palmer",
      "Sex": "F",
      "Team": "Australia",
      "Year": 2012,
      "City": "London",
      "Sport": "Swimming",
      "Event": "Swimming Women's 4 x 200 metres Freestyle Relay",
      "Medal": "Silver"
    },
    {
      "ID": 94947,
      "Name": "Adam Robert Pine",
      "Sex": "M",
      "Team": "Australia",
      "Year": 2008,
      "City": "Beijing",
      "Sport": "Swimming",
      "Event": "Swimming Men's 4 x 100 metres Medley Relay",
      "Medal": "Silver"
    },
    {
      "ID": 52358,
      "Name": "Ryosuke Irie",
      "Sex": "M",
      "Team": "Japan",
      "Year": 2012,
      "City": "London",
      "Sport": "Swimming",
      "Event": "Swimming Men's 200 metres Backstroke",
      "Medal": "Silver"
    },
    {
      "ID": 60893,
      "Name": "Kosuke Kitajima",
      "Sex": "M",
      "Team": "Japan",
      "Year": 2012,
      "City": "London",
      "Sport": "Swimming",
      "Event": "Swimming Men's 4 x 100 metres Medley Relay",
      "Medal": "Silver"
    },
    {
      "ID": 28734,
      "Name": "Madeline Jane DiRado",
      "Sex": "F",
      "Team": "United States",
      "Year": 2016,
      "City": "Rio de Janeiro",
      "Sport": "Swimming",
      "Event": "Swimming Women's 400 metres Individual Medley",
      "Medal": "Silver"
    },
    {
      "ID": 42803,
      "Name": "Matthew Grevers",
      "Sex": "M",
      "Team": "United States",
      "Year": 2008,
      "City": "Beijing",
      "Sport": "Swimming",
      "Event": "Swimming Men's 100 metres Backstroke",
      "Medal": "Silver"
    },
    {
      "ID": 100315,
      "Name": "Kimberly Susan Rhode",
      "Sex": "F",
      "Team": "United States",
      "Year": 2008,
      "City": "Beijing",
      "Sport": "Shooting",
      "Event": "Shooting Women's Skeet",
      "Medal": "Silver"
    },
    {
      "ID": 32517,
      "Name": "Matthew D. Emmons",
      "Sex": "M",
      "Team": "United States",
      "Year": 2008,
      "City": "Beijing",
      "Sport": "Shooting",
      "Event": "Shooting Men's Small-Bore Rifle, Prone, 50 metres",
      "Medal": "Silver"
    },
    {
      "ID": 116360,
      "Name": "Eamon Wade Sullivan",
      "Sex": "M",
      "Team": "Australia",
      "Year": 2008,
      "City": "Beijing",
      "Sport": "Swimming",
      "Event": "Swimming Men's 4 x 100 metres Freestyle Relay",
      "Medal": "Bronze"
    },
    {
      "ID": 118617,
      "Name": "Matthew Stephen C. Targett",
      "Sex": "M",
      "Team": "Australia",
      "Year": 2008,
      "City": "Beijing",
      "Sport": "Swimming",
      "Event": "Swimming Men's 4 x 100 metres Freestyle Relay",
      "Medal": "Bronze"
    },
    {
      "ID": 76551,
      "Name": "Takeshi Matsuda",
      "Sex": "M",
      "Team": "Japan",
      "Year": 2012,
      "City": "London",
      "Sport": "Swimming",
      "Event": "Swimming Men's 200 metres Butterfly",
      "Medal": "Bronze"
    },
    {
      "ID": 9460,
      "Name": "Elizabeth Lyon Beisel",
      "Sex": "F",
      "Team": "United States",
      "Year": 2012,
      "City": "London",
      "Sport": "Swimming",
      "Event": "Swimming Women's 200 metres Backstroke",
      "Medal": "Bronze"
    },
    {
      "ID": 23426,
      "Name": "Natalie Anne Coughlin",
      "Sex": "F",
      "Team": "United States",
      "Year": 2008,
      "City": "Beijing",
      "Sport": "Swimming",
      "Event": "Swimming Women's 200 metres Individual Medley",
      "Medal": "Bronze"
    }
  ]